### ISSUE TITLE
After creating models, opening index.js breaks

### ISSUE THREAD

**Issue by coltaemanuela** [coltaemanuela/Sequelize-Models#1]
The models are being created correctly, the many-to-many relationship is established, but, when trying to access the index.js and, effectively, access the application,  I get the following error: 
![error](https://cloud.githubusercontent.com/assets/10262414/23985293/eb016a08-0a26-11e7-91b2-c9aabf68ad0a.png)
![error2](https://cloud.githubusercontent.com/assets/10262414/23985296/ecdbd1ba-0a26-11e7-8277-659a6e460242.png)

**Comment by IonicaBizau** [comment]
@coltaemanuela This is fixed via #2, right? 💥

**Comment by coltaemanuela** [comment]
Yes, now it's working properly. Thank you! 🎉 🎉 🎉
